# Generated by Django 4.1.6 on 2023-02-27 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, null=True)),
                ('author_image', models.ImageField(null=True, upload_to='uploads')),
                ('highlights', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='author_image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='topic',
            name='author_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='highlights',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
