# Generated by Django 4.1.6 on 2023-02-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_content_topic_author_image_topic_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.topic'),
            preserve_default=False,
        ),
    ]
