# Generated by Django 4.1.6 on 2023-02-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_content_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='highlights',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.content')),
            ],
        ),
    ]
